web:
  image: ryanjbaxter/ocr-web
  ports:
    - "8080:8080"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
  links:
    - eureka
    - participants
    - races
    - zipkin
    - config

races:
  image: ryanjbaxter/ocr-races
  ports:
    - "8282:8282"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
  links:
    - eureka
    - participants
    - zipkin
    - config

participants:
  image: ryanjbaxter/ocr-participants
  ports:
    - "8181:8181"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
  links:
    - eureka
    - zipkin
    - config

hystrix:
  image: ryanjbaxter/ocr-hystrix-dashboard
  ports:
    - "8383:8383"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
  links:
    - eureka
    - races
    - participants
    - web
    - config

zipkin:
  image: ryanjbaxter/ocr-zipkin
  ports:
    - "9411:9411"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
  links:
    - config

eureka:
  image: ryanjbaxter/ocr-eureka
  ports:
    - "8761:8761"
  links:
    - config

config:
  image: ryanjbaxter/ocr-config-server
  ports:
    - "8888:8888"
