web:
  image: ryanjbaxter/ocr-web
  ports:
    - "8080:8080"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
  links:
    - eureka
    - participants
    - races
    - zipkin

races:
  image: ryanjbaxter/ocr-races
  ports:
    - "8282:8282"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
  links:
    - eureka
    - participants
    - zipkin

participants:
  image: ryanjbaxter/ocr-participants
  ports:
    - "8181:8181"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
  links:
    - eureka
    - zipkin

hystrix:
  image: ryanjbaxter/ocr-hystrix-dashboard
  ports:
    - "8383:8383"
  environment:
    - SPRING_PROFILES_ACTIVE=docker
  links:
    - eureka
    - races
    - participants
    - web

zipkin:
  image: ryanjbaxter/ocr-zipkin
  ports:
    - "9411:9411"
  environment:
    - SPRING_PROFILES_ACTIVE=docker

eureka:
  image: ryanjbaxter/ocr-eureka
  ports:
    - "8761:8761"
